name: "My CI (linting, testing, building, chromatic)"

on: 
  push:
    branches: ['main']
  pull_request: 
    branches: ['main']

jobs:
  pipeline-with-chromatic:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm ci

      - name: linting ts
        if: always()
        run: npm run lint:ts

      - name: linting css
        if: always()
        run: npm run lint:css

      - name: unit testing
        if: always()
        run: npm run test:unit
        
      # - name: build production
      #   if: always()
      #   run: npm run build:prod

      # - name: Publish to Chromatic
      #   uses: chromaui/action@latest
      #   with:
      #     projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}